name: Fetch API Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch API Data
        run: |
          curl -o api-data.json http://emi-hfu.pea.co.th/API_BILL/InfoAllMRU?search=
          git add api-data.json
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Update API data"
          git push
